version: '2'

services:
  keops:
    build:
      context: .
      dockerfile: Dockerfile
    image: keops:latest
    container_name: keops
    restart: always
    environment: 
      - KEOPS_DB_NAME=keopsdb
      - KEOPS_DB_HOST=keopsdb
      - KEOPS_DB_USER=keopsdb
      - KEOPS_DB_PASS=PASSWORD_FOR_USER_KEOPS
      - KEOPS_DB_PORT=5432
      - POSTGRESPASSWORD=PASSWORD_FOR_POSTGRES
      - KEOPS_HELPER_HOST=
      - KEOPS_HELPER_EMAIL=
      - KEOPS_HELPER_PASSWORD=
    ports:
      - "8080:80"
    depends_on:
      - keopsdb
    networks:
      - keops
      
  keopsdb:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: keopsdb:latest
    container_name: keopsdb
    networks:
      - keops
    environment:
      - POSTGRESPASSWORD=PASSWORD_FOR_POSTGRES
      - KEOPS_ROOT_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  keops:

volumes:
  postgres:
